services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/docjyj/simple-craft-admin:main
    container_name: simple-craft-admin
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - '80:3000'
    volumes:
      - ./config:/app/config
      - ./minecraft:/app/minecraft
      - ./backup:/app/backup
    restart: unless-stopped
