name: Markdown Link Check

on:
  pull_request:
    paths:
      - '**.md'
  push:
    branches:
      - main
    tags:
      - 'v*'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Markdown Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
